### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by jorendorff** [tc39/proposal-do-expressions#23]
The proposal says:

> * key refactoring principles:
>   * `do { <expr>; }` equivalent to `<expr>`
>   * `(do { <stmt> };)` equivalent to `{ <stmt> }`

On the last line quoted here, I think `;` and `)` should be swapped: `(do { <stmt> });`.

**Comment by bakkot** [comment]
The relevant text has been removed as of https://github.com/tc39/proposal-do-expressions/pull/54, so I'm going to close this.

(I removed it because it's no longer precisely true: I resolved https://github.com/tc39/proposal-do-expressions/issues/48, with the effect that `eval('0; do { ; };')` is `undefined` rather than 0, as the the second bullet point would imply.)
